### ISSUE TITLE
Need to install PIL?

### ISSUE THREAD

**Issue by jesford** [rouseguy/scipyUS2016_dl-image#1]
I followed the installation instructions, but when when I run `python check_env.py` I get the message: `PIL:: No module named 'PIL'`

But it seems PIL is not compatible with Python3:

```
$ conda install pil
Fetching package metadata .......
Solving package specifications: ....

The following specifications were found to be in conflict:
  - pil
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

Do we need PIL for the tutorial?

Thanks!!

**Comment by rouseguy** [comment]
Please install using the following command

`pip install pillow`

**Comment by syedfaizalex** [comment]
still not working even after installing pillow

**Comment by cecilmalone** [comment]
Try this.

conda install -c anaconda pil

**Comment by aaryapatel007** [comment]
still not working.....

**Comment by amitkaps** [comment]
Please check out our newer deep learning repo for updated material - https://github.com/amitkaps/deep-learning
